### ISSUE TITLE
第 52 题：怎么让一个 div 水平垂直居中

### ISSUE THREAD

**Issue by zeroone001** [Advanced-Frontend/Daily-Interview-Question#92]
1.  
```css 
div.parent {
    display: flex;
    justify-content: center;
    align-items: center;
}
```
2.
```css
div.parent {
    position: relative; 
}
div.child {
    position: absolute; 
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);  
}
```
3.
```css
div.parent {
    display: grid;
}
div.child {
    justify-self: center;
    align-self: center;
}
```

**Comment by Feather130** [comment]
楼上总结的差不多了。再加一种
```javascript
div.parent{
  display:flex;
}
div.child{
  margin:auto;
}
```

**Comment by cleverboy32** [comment]
div.parent {
display: table;
}
div.child {
display: table-cell
vertical-align: middle;
text-align: center;
}

**Comment by yhlben** [comment]
补充一个，使用 table-cell 的方式：
```css
.parent {
        display: table-cell;
        height: 200px;
        width: 200px;
        background-color: orange;
        text-align: center;
        vertical-align: middle;
}
 .child {
        display: inline-block;
        width: 100px;
        height: 100px;
        background-color: blue;
}
```

```html
<div class="parent">
      <div class="child"></div>
</div>
```

**Comment by Moriarty02** [comment]
水平垂直居中有好多种实现方式，主要就分为两类不定宽高和定宽高
以在body下插入一个div为例
1. 定宽高
使用定位+margin
```css
element.style {
    position: absolute;
    left: 50%;
    top: 50%;
    margin-left: -250px;
    margin-top: -250px;
    width: 500px;
    height: 500px;
    background: yellow;
    z-index: 1;
}
```
使用定位+transfrom
```css

element.style {
    position: absolute;
    left: 50%;
    top: 50%;
    width: 500px;
    height: 500px;
    background: yellow;
    z-index: 1;
    transform: translate3d(-50%,-50%,0);
}
```
2. 不定宽高
不定宽高的方法基本都适用于定宽高的情况
这里把div的宽高按照内容展开
使用定位+transform同样是适用的
```css

element.style {
    position: absolute;
    left: 50%;
    top: 50%;
    background: yellow;
    z-index: 1;
    transform: translate3d(-50%,-50%,0);
}
```
还有一些其他的方法比如使用父容器使用flex，grid，table
这两个楼上也提到了，是可以实现的，但是在实际应用中，
因为改变了父容器的display，在多个子节点反而不好用了

**Comment by cb3570594** [comment]
> 楼上总结的差不多了。再加一种
> 
> ```css
> div.parent{
>   display:flex;
> }
> div.child{
>   margin:auto;
> }
> ```

同理：
`div.parent{
  display:grid;
}
div.child{
  margin:auto;
}
`

**Comment by zeroone001** [comment]
> div.parent {
> display: table;
> }
> div.child {
> display: table-cell
> vertical-align: middle;
> text-align: center;
> }

需要再补充一个@cleverboy32
```css
div.grandson {
    display:inline-block;
    width: 10px;
    height: 10px;
}
```

**Comment by sohoorc** [comment]
```
1. 
div.parent {
     display:flex;
      justify-content:center;
     align-items:center;
}

2.
div.parent {
    position:relative;
}

div.child{
    position:absolute;
    top:50%;
    left:50%;
    transform:translate(-50%,-50%);
}
```

**Comment by Leo928** [comment]
我总结的方法：https://juejin.im/post/5ca1a585f265da30dc7ac3f7

**Comment by yiqingfeng** [comment]
[](url)

> 补充一个，使用 table-cell 的方式：
> 
> ```css
> .parent {
>         display: table-cell;
>         height: 200px;
>         width: 200px;
>         background-color: orange;
>         text-align: center;
>         vertical-align: middle;
> }
>  .child {
>         display: inline-block;
>         width: 100px;
>         height: 100px;
>         background-color: blue;
> }
> ```
> 
> ```
> <div class="parent">
>       <div class="child"></div>
> </div>
> ```

table-cell 是不支持设置 width: 100%;  想让 `.parent` 和 其容器宽度一致最好设置一个 `dispaly: table;` 父容器。

```html
<div class="parent-fix">
  <div class="parent">
    <div class="child">DEMO</div>
  </div>
</div>
```

```css
.parent-fix {
  display: table;
  width: 100%;
}
.parent {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
  height: 200px;
  background-color: #ccc;
}
.child {
  display: inline-block;
  background-color: #000;
  line-height: 50px;
  color: #fff;
}
```

**Comment by cleverboy32** [comment]
在 parent 有宽高的时候， child 已经垂直居中了

**Comment by zeroone001** [comment]
> @zeroone001 在 parent 有宽高的时候， child 已经垂直居中了

不行
display: table-cell; 这个居中不了，必须要第三个元素在child里面

**Comment by XinChou16** [comment]
[100%高度的 after 加上 inline-block](https://jsbin.com/gevezudibi/edit?html,css,output)
```html
<div class="box">
    <div class="center">
</div>
```
```css
.box {
  width: 500px;
  height: 500px;
  text-align: center; /*center*/
}
.box::after {
  content: '';
  display: inline-block;
  width: 0;
  height: 100%;
  vertical-align: middle;
}
.center {
  display: inline-block;
  width: 100px;
  height: 100px;
  vertical-align: middle;/*center*/
}
```

**Comment by Caitingwei** [comment]
**```
// 1. line-height + text-algin
.parent {
  height: 100px;
  line-height: 100px;
  text-align: center;
}
.child {
}

// 2. text-align + vertail-align
.parent {
  text-align: center;
}
.child {
  display: inline-block;
  vertical-align: middle;
}

// 3. table-cell + vertail-align
.parent {
  display: table-cell;
  vertical-align: middle;
}
.child {
}

// 4. position + margin
.parent {
  position: relative;
}
.child {
  width: 100px;
  height: 100px;
  position: absolute;
  left: calc(50% - 50px);
  top: calc(50% - 50px);
}

// 5.position + transform 
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

// 6. flex
.parent {
  display: flex;
}
.child {
  align-items: center;
  justify-content: center;
}
```**

**Comment by Caitingwei** [comment]
```
// 1. line-height + text-algin
.parent {
  height: 100px;
  line-height: 100px;
  text-align: center;
}
.child {
}

// 2. text-align + vertail-align
.parent {
  text-align: center;
}
.child {
  display: inline-block;
  vertical-align: middle;
}

// 3. table-cell + vertail-align
.parent {
  display: table-cell;
  vertical-align: middle;
}
.child {
}

// 4. position + margin
.parent {
  position: relative;
}
.child {
  width: 100px;
  height: 100px;
  position: absolute;
  left: calc(50% - 50px);
  top: calc(50% - 50px);
}

// 5.position + transform 
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

// 6. flex
.parent {
  display: flex;
}
.child {
  align-items: center;
  justify-content: center;
}
```

**Comment by Caitingwei** [comment]
```css
// 1. line-height + text-algin
.parent {
  height: 100px;
  line-height: 100px;
  text-align: center;
}
.child {
}

// 2. text-align + vertail-align
.parent {
  text-align: center;
}
.child {
  display: inline-block;
  vertical-align: middle;
}

// 3. table-cell + vertail-align
.parent {
  display: table-cell;
  vertical-align: middle;
}
.child {
}

// 4. position + margin
.parent {
  position: relative;
}
.child {
  width: 100px;
  height: 100px;
  position: absolute;
  left: calc(50% - 50px);
  top: calc(50% - 50px);
}

// 5.position + transform 
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

// 6. flex
.parent {
  display: flex;
}
.child {
  align-items: center;
  justify-content: center;
}
```

**Comment by huijingL** [comment]
楼上大神们指出的很全了，

我指出一点： 
使用 margin-left 和 margin-top, 相对的是父元素，
transform： translate 相对的自身，
这是他们的一点区别，实际上我是想问一下，他们还有没有其他的区别 ，望后续大神指出；

前端小白，有错勿怪，感谢指正

**Comment by luichooy** [comment]
> ```css
> arent
> ```

方法2只能做到水平居中，方法3倒是div.parent的宽度和div.child宽度一样，且设置width样式无效

**Comment by luichooy** [comment]
> ```css
> // 1. line-height + text-algin
> .parent {
>   height: 100px;
>   line-height: 100px;
>   text-align: center;
> }
> .child {
> }
> 
> // 2. text-align + vertail-align
> .parent {
>   text-align: center;
> }
> .child {
>   display: inline-block;
>   vertical-align: middle;
> }
> 
> // 3. table-cell + vertail-align
> .parent {
>   display: table-cell;
>   vertical-align: middle;
> }
> .child {
> }
> 
> // 4. position + margin
> .parent {
>   position: relative;
> }
> .child {
>   width: 100px;
>   height: 100px;
>   position: absolute;
>   left: calc(50% - 50px);
>   top: calc(50% - 50px);
> }
> 
> // 5.position + transform 
> .parent {
>   position: relative;
> }
> .child {
>   position: absolute;
>   top: 50%;
>   left: 50%;
>   transform: translate(-50%, -50%);
> }
> 
> // 6. flex
> .parent {
>   display: flex;
> }
> .child {
>   align-items: center;
>   justify-content: center;
> }
> ```

方法2 只能水平居中，方法3导致div.parent宽度和div.parent宽度一样，且设置width样式无效

**Comment by banli17** [comment]
> ```css
> div.parent {
> display: table;
> }
> div.child {
> display: table-cell
> vertical-align: middle;
> text-align: center;
> }
> ```

这个设置table-cell 的盒子会占满父盒子，里面的文字才能居中。

**Comment by Valar103769** [comment]
.child{width:fit-content;margin:0 auto}

**Comment by CathyZYF** [comment]
> ```sass
> div.parent {
>     font-size: 0;
>     text-align: center;
>     &::before {
>         content: "";
>         display: inline-block;
>         width: 0;
>         height: 100%;
>         vertical-align: middle;
>     }
> }
> div.child{
>   display: inline-block;
>   vertical-align: middle;
> }
> ```
能说一下这种实现方式的原理吗

**Comment by MarshallShady** [comment]
> > ```sass
> > div.parent {
> >     font-size: 0;
> >     text-align: center;
> >     &::before {
> >         content: "";
> >         display: inline-block;
> >         width: 0;
> >         height: 100%;
> >         vertical-align: middle;
> >     }
> > }
> > div.child{
> >   display: inline-block;
> >   vertical-align: middle;
> > }
> > ```
> 
> 能说一下这种实现方式的原理吗

这个我前几天刚在张鑫旭的《CSS世界》里面第一次看到，原理就是（基于我个人的理解）：通过伪类撑开父元素高度，设置inline-block和vertical-align:middle后，里面的元素会基于中间的文字准线居中对齐（学生时代的英语本子里面写字母，都是4条线形成三个空白区域，文字的对齐就是根据这几条线的）vertical-align更多信息可以看看[张鑫旭博文](https://www.zhangxinxu.com/wordpress/2010/05/%e6%88%91%e5%af%b9css-vertical-align%e7%9a%84%e4%b8%80%e4%ba%9b%e7%90%86%e8%a7%a3%e4%b8%8e%e8%ae%a4%e8%af%86%ef%bc%88%e4%b8%80%ef%bc%89/)；
然后，按照正常的理解，此时文字的准线应该是div.parent的顶部，但是由于父元素position:static(默认），那么伪类只能下移，使得此时文字的基准线就是整个div.parent的中心了，另外vertical-align只影响inline或者inline-block的，所以div.child设置vertical-align就能居中了。
以上是我个人的理解，有很多表达不清楚的地方，更详细的内容还是推荐张鑫旭的博文。

**Comment by MarshallShady** [comment]
> > > ```sass
> > > div.parent {
> > >     font-size: 0;
> > >     text-align: center;
> > >     &::before {
> > >         content: "";
> > >         display: inline-block;
> > >         width: 0;
> > >         height: 100%;
> > >         vertical-align: middle;
> > >     }
> > > }
> > > div.child{
> > >   display: inline-block;
> > >   vertical-align: middle;
> > > }
> > > ```
> > 
> > 
> > 能说一下这种实现方式的原理吗
> 
> 这个我前几天刚在张鑫旭的《CSS世界》里面第一次看到，原理就是（基于我个人的理解）：通过伪类撑开父元素高度，设置inline-block和vertical-align:middle后，里面的元素会基于中间的文字准线居中对齐（学生时代的英语本子里面写字母，都是4条线形成三个空白区域，文字的对齐就是根据这几条线的）vertical-align更多信息可以看看[张鑫旭博文](https://www.zhangxinxu.com/wordpress/2010/05/%e6%88%91%e5%af%b9css-vertical-align%e7%9a%84%e4%b8%80%e4%ba%9b%e7%90%86%e8%a7%a3%e4%b8%8e%e8%ae%a4%e8%af%86%ef%bc%88%e4%b8%80%ef%bc%89/)；
> 然后，按照正常的理解，此时文字的准线应该是div.parent的顶部，但是由于父元素position:static(默认），那么伪类只能下移，使得此时文字的基准线就是整个div.parent的中心了，另外vertical-align只影响inline或者inline-block的，所以div.child设置vertical-align就能居中了。
> 以上是我个人的理解，有很多表达不清楚的地方，更详细的内容还是推荐张鑫旭的博文。

更正一下，其实和div.parent的position没有关系，只要你的伪类不设置absolute之类的布局让他脱离文档流，这种居中方法就能生效。

**Comment by lyandzao** [comment]
可以用calc来计算，这样代码少一点
.parent {
      border: 1px solid;
      width: 1000px;
      height: 1000px;
    }

    .child {
      position: relative;
      border: 1px solid;
      width: 100px;
      height: 100px;
      top: calc(50% - 50px);
      left: calc(50% - 50px);
    }

**Comment by bowenxiaoCUHKSZ** [comment]
> ```
> <div class="parent">
>   <div class="child"></div>
> </div>
> ```
> 
> 
> ```css
> div.parent {
>     display: flex;
>     justify-content: center;
>     align-items: center;
> }
> ```
> 
> 
> ```css
> div.parent {
>     position: relative; 
> }
> div.child {
>     position: absolute; 
>     top: 50%;
>     left: 50%;
>     transform: translate(-50%, -50%);  
> }
> /* 或者 */
> div.child {
>     width: 50px;
>     height: 10px;
>     position: absolute;
>     top: 50%;
>     left: 50%;
>     margin-left: -25px;
>     margin-top: -5px;
> }
> /* 或 */
> div.child {
>     width: 50px;
>     height: 10px;
>     position: absolute;
>     left: 0;
>     top: 0;
>     right: 0;
>     bottom: 0;
>     margin: auto;
> }
> ```
> 
> 
> ```css
> div.parent {
>     display: grid;
> }
> div.child {
>     justify-self: center;
>     align-self: center;
> }
> ```
> 
> 
> ```sass
> div.parent {
>     font-size: 0;
>     text-align: center;
>     &::before {
>         content: "";
>         display: inline-block;
>         width: 0;
>         height: 100%;
>         vertical-align: middle;
>     }
> }
> div.child{
>   display: inline-block;
>   vertical-align: middle;
> }
> ```
提个建议，可以在每一种实现上写一下思想和场景

**Comment by huwenkang99** [comment]
> 楼上大神们指出的很全了，
> 
> 我指出一点：
> 使用 margin-left 和 margin-top, 相对的是父元素，
> transform： translate 相对的自身，
> 这是他们的一点区别，实际上我是想问一下，他们还有没有其他的区别 ，望后续大神指出；
> 
> 前端小白，有错勿怪，感谢指正

margin是给自己加个外边框，是相对自身原来的位置来变化吧

**Comment by leohongbing** [comment]
学无止境~
div.parent  {
    position: relative;
  }
  
  div.child  {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
  }

**Comment by zhuangyin8** [comment]
[Centering in CSS: A Complete Guide]( https://css-tricks.com/centering-css-complete-guide/#center-horizontally)

**Comment by ciming** [comment]
```css
div.parent{
   display:grid;
   place-items: center;
}
```

**Comment by brilliant-js** [comment]
1. 设置绝对定位

```css
div.parent {
  position: relative;
}
div.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

2. 外层容器设置 display: flex

```css
.container {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

3. grid 布局

```css
div.parent {
  display: grid;
}
div.child {
  justify-self: center;
  align-self: center;
}
```

4. 冷门操作

```css
div.parent {
  display: flex;
}
div.child {
  margin: auto;
}
```

5. table 布局

```css
div.parent {
  display: table;
}
div.child {
  display: table-cell
  vertical-align: middle;
  text-align: center;
}
```

6. table-cell

```css
.parent {
  display: table-cell;
  height: 200px;
  width: 200px;
  background-color: orange;
  text-align: center;
  vertical-align: middle;
}
.child {
  display: inline-block;
  width: 100px;
  height: 100px;
  background-color: blue;
}
```
